// 筹码筛选 Worker (Service Worker) v7 — Exchange Proxy + Source Guard
const KV_HTML_KEY='dashboard_html';
function json(d,s=200){return new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*'}})}
function html(c,s=200){return new Response(c,{status:s,headers:{'Content-Type':'text/html; charset=utf-8','Access-Control-Allow-Origin':'*'}})}
function normalizePath(p){for(const pre of['/screener','']){if(p===pre||p===pre+'/')return'/';if(p.startsWith(pre+'/'))return p.slice(pre.length)}return p}
function matchMarketKey(ba,sym,map){const u=(ba||'').toUpperCase();if(map[u])return map[u];if(map[sym])return map[sym];const c=u.replace(/^\\d{4,}x?/,'');if(c&&c!==u&&map[c])return map[c];return null}
function crossValidateRatio(a,b){if(a==null||b==null)return null;const mx=Math.max(a,b),mn=Math.min(a,b);if(mx===0)return null;const d=(mx-mn)/mx;if(d>0.3)return{conflicted:true,cmc_ratio:Math.round(a*10000)/10000,cg_ratio:Math.round(b*10000)/10000,discrepancy:Math.round(d*100)};return null}
async function refreshData(kv,env){
  const pR=await kv.get('exchange_proxy').catch(()=>null),pU=await kv.get('exchange_proxy_updated').catch(()=>null),pA=pU?Date.now()-new Date(pU).getTime():Infinity,has=pR&&pA<5*60*1000;
  let bn=null,bb=null,ok=null,src=0;
  if(has){try{const p=JSON.parse(pR);if(p.binance){bn=p.binance;src++}if(p.bybit){bb=p.bybit;src++}if(p.okx){ok=p.okx;src++}}catch(e){}}
  if(!has){const[a,b,c]=await Promise.allSettled([fBN(),fBB(),fOK()]);if(a.status==='fulfilled'){bn=a.value;src++}if(b.status==='fulfilled'){bb=b.value;src++}if(c.status==='fulfilled'){ok=c.value;src++}}
  const dbg={};dbg.Binance=bn?{t:bn.length,ok:true}:{e:'unavail'};dbg.Bybit=bb?{t:bb.length,ok:true}:{e:'unavail'};dbg.OKX=ok?{t:ok.length,ok:true}:{e:'unavail'};dbg.proxy={active:has,s:src};await kv.put('exchange_debug',JSON.stringify(dbg)).catch(()=>{});
  const cmc=await fCMC(env).catch(()=>null);let cg=null;const lC=await kv.get('last_cg_fetch').catch(()=>null);if(!lC||Date.now()-new Date(lC).getTime()>36e5){cg=await fCG(env).catch(()=>null);if(cg)await kv.put('last_cg_fetch',new Date().toISOString()).catch(()=>{})}
  const ex=[];{const s={};for(const r of[bn,bb,ok])if(r)for(const row of r){const sym=row.symbol;if(!s[sym]||(row.volume_24h_usdt||0)>(s[sym].volume_24h_usdt||0))s[sym]=row}for(const k of Object.keys(s))ex.push(s[k])}
  function va(coin,k){if(!cg)return coin;const g=cg[k]||matchMarketKey(coin.base_asset,coin.symbol,cg);if(!g)return coin;const cf=crossValidateRatio(coin.circulating_ratio,g.circulating_ratio);if(cf){coin.data_conflict=true;coin.discrepancy_pct=cf.discrepancy;coin.cmc_ratio=cf.cmc_ratio;coin.cg_ratio=cf.cg_ratio;if(coin.market_cap!=null&&g.market_cap!=null&&cf.cg_ratio<cf.cmc_ratio*0.5&&g.market_cap<coin.market_cap*0.5)coin.stale_cg_data=true;coin.unlock_risk=uL((coin.circulating_ratio+g.circulating_ratio)/2)}return coin}
  if(ex.length>0&&cmc&&src>=2){const m=[];for(const row of ex){const ba=(row.base_asset||'').toUpperCase(),c=matchMarketKey(ba,row.symbol,cmc),mcap=c?c.market_cap:null,cr=c?c.circulating_ratio:null;let coin={symbol:row.symbol,name:c?c.name:ba,base_asset:row.base_asset,price:row.price,market_cap:mcap,circulating_supply:c?c.circulating_supply:null,total_supply:c?c.total_supply:null,max_supply:c?c.max_supply:null,circulating_ratio:cr,cmc_rank:c?c.cmc_rank:null,volume_24h_usdt:row.volume_24h_usdt,percent_change_7d:c?c.percent_change_7d:null,change_24h_pct:row.change_24h_pct,amplitude_24h_pct:row.amplitude_24h_pct,star_rating:aS(mcap,cr,false),unlock_risk:uL(cr),momentum_alert:!!(c&&c.percent_change_7d!=null&&c.percent_change_7d>0&&row.amplitude_24h_pct>10)};coin=va(coin,ba);coin.star_rating=aS(coin.market_cap,coin.circulating_ratio,coin.data_conflict,coin.stale_cg_data);m.push(coin)}
    const f=m.filter(r=>r.market_cap!=null&&r.market_cap>=15e6);if(f.length>0){await kv.put('data',JSON.stringify(f));await kv.put('last_updated',new Date().toISOString());await kv.put('count',String(f.length));console.log('B1:',f.length,'coins');return}}
  if(cmc){const exMap={};for(const row of ex){const k=(row.base_asset||'').toUpperCase();exMap[k]=row;exMap[row.symbol]=row};const coins=[];for(const[sym,c]of Object.entries(cmc)){if(c.market_cap==null||c.market_cap<15e6)continue;const xr=exMap[sym]||exMap[(c.symbol||'').toUpperCase()]||matchMarketKey((c.symbol||'').toUpperCase(),sym,exMap);let coin={symbol:c.symbol||'',name:c.name||(c.symbol||'').toUpperCase(),base_asset:(c.symbol||'').toUpperCase(),price:xr?xr.price:c.price,market_cap:c.market_cap,circulating_supply:c.circulating_supply,total_supply:c.total_supply,max_supply:c.max_supply,circulating_ratio:c.circulating_ratio,cmc_rank:c.cmc_rank,volume_24h_usdt:xr?xr.volume_24h_usdt:c.volume_24h_usdt,percent_change_7d:c.percent_change_7d,change_24h_pct:xr?xr.change_24h_pct:null,amplitude_24h_pct:xr?xr.amplitude_24h_pct:null,star_rating:aS(c.market_cap,c.circulating_ratio,false),unlock_risk:uL(c.circulating_ratio),momentum_alert:!!(xr&&c.percent_change_7d>0&&xr.amplitude_24h_pct>10)};coin=va(coin,sym);if(coin.circulating_ratio>1){coin.supply_data_error=true;coin.circulating_ratio=1};if(coin.circulating_ratio>=1&&(!coin.volume_24h_usdt||coin.volume_24h_usdt<100)){coin.low_confidence_supply=true};coin.star_rating=aS(coin.market_cap,coin.circulating_ratio,coin.data_conflict||coin.supply_data_error,coin.stale_cg_data);coins.push(coin)}
    if(coins.length>0){await kv.put('data',JSON.stringify(coins));await kv.put('last_updated',new Date().toISOString());await kv.put('count',String(coins.length));console.log('B2:',coins.length,'coins');return}}
  if(ex.length>0){const coins=ex.map(r=>({symbol:r.symbol,name:(r.base_asset||'').toUpperCase(),base_asset:r.base_asset,price:r.price,market_cap:null,circulating_supply:null,total_supply:null,max_supply:null,circulating_ratio:null,cmc_rank:null,volume_24h_usdt:r.volume_24h_usdt,percent_change_7d:null,change_24h_pct:r.change_24h_pct,amplitude_24h_pct:r.amplitude_24h_pct,star_rating:0,unlock_risk:uL(null),momentum_alert:false}));await kv.put('data',JSON.stringify(coins));await kv.put('last_updated',new Date().toISOString());await kv.put('count',String(coins.length));console.log('B3:',coins.length,'coins')}
}
async function fBB(){const c=new AbortController,t=setTimeout(()=>c.abort(),15e3);try{const[i,tk]=await Promise.all([fetch('https://api.bybit.com/v5/market/instruments-info?category=linear',{signal:c.signal}),fetch('https://api.bybit.com/v5/market/tickers?category=linear',{signal:c.signal})]);if(!i.ok)throw new Error('BB i:'+i.status);if(!tk.ok)throw new Error('BB t:'+tk.status);const id=await i.json(),syms=new Set(id.result.list.filter(s=>s.status==='Trading'&&s.quoteCoin==='USDT'&&s.contractType==='LinearPerpetual').map(s=>s.symbol)),td=await tk.json(),map=new Map;for(const t of td.result.list)map.set(t.symbol,t);const rows=[];for(const s of syms){const t=map.get(s);if(!t)continue;const p=parseFloat(t.lastPrice),h=parseFloat(t.highPrice24h),l=parseFloat(t.lowPrice24h),pc=parseFloat(t.price24hPcnt||'0')*100;if(isNaN(p)||p<=0)continue;rows.push({symbol:s,base_asset:s.replace('USDT',''),price:p,change_24h_pct:Math.round(pc*100)/100,amplitude_24h_pct:Math.round(((h-l)/p)*100*100)/100,volume_24h_usdt:parseFloat(t.turnover24h||'0')})}return rows}finally{clearTimeout(t)}}
async function fBN(){const c=new AbortController,t=setTimeout(()=>c.abort(),15e3);try{const r=await fetch('https://fapi.binance.com/fapi/v1/ticker/24hr',{signal:c.signal});if(!r.ok)throw new Error('BN:'+r.status);const d=await r.json(),rows=[];for(const t of d){if(!t.symbol.endsWith('USDT'))continue;const p=parseFloat(t.lastPrice),h=parseFloat(t.highPrice),l=parseFloat(t.lowPrice);if(isNaN(p)||p<=0)continue;rows.push({symbol:t.symbol,base_asset:t.symbol.replace('USDT',''),price:p,change_24h_pct:Math.round(parseFloat(t.priceChangePercent||'0')*100)/100,amplitude_24h_pct:h&&l&&h>0&&l>0?Math.round(((h-l)/p)*100*100)/100:0,volume_24h_usdt:parseFloat(t.quoteVolume||'0')})}return rows}finally{clearTimeout(t)}}
async function fOK(){const c=new AbortController,t=setTimeout(()=>c.abort(),15e3);try{const r=await fetch('https://www.okx.com/api/v5/market/tickers?instType=SWAP',{signal:c.signal});if(!r.ok)throw new Error('OK:'+r.status);const d=await r.json();if(!d.data)return[];const rows=[];for(const t of d.data){if(!t.instId.endsWith('-USDT-SWAP'))continue;const p=parseFloat(t.last),h=parseFloat(t.high24h),l=parseFloat(t.low24h),o=parseFloat(t.open24h);if(isNaN(p)||p<=0)continue;const ba=t.instId.replace('-USDT-SWAP','');rows.push({symbol:ba+'USDT',base_asset:ba,price:p,change_24h_pct:o&&o>0?Math.round(((p-o)/o)*100*100)/100:0,amplitude_24h_pct:h&&l&&h>0&&l>0?Math.round(((h-l)/p)*100*100)/100:0,volume_24h_usdt:parseFloat(t.volCcy24h||'0')})}return rows}finally{clearTimeout(t)}}
async function fCMC(env){const k=env?.CMC_API_KEY||(typeof CMC_API_KEY!==`undefined`?CMC_API_KEY:null);if(!k)return null;try{const c=new AbortController,t=setTimeout(()=>c.abort(),1e4);try{const r=await fetch('https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?start=1&limit=1000&convert=USD',{headers:{'X-CMC_PRO_API_KEY':k,'Accept':'application/json'},signal:c.signal});if(r.ok){const d=await r.json();return pC(d)}try{const e=await r.json();console.error('CMC err:',r.status,e)}catch(e){}}finally{clearTimeout(t)}}catch(e){console.error('CMC fetch err:',e)}return null}
function pC(d){const m={};for(const c of d.data){const q=c.quote.USD,cs=c.circulating_supply,ts=c.total_supply,ms=c.max_supply;let cr=null;if(ts&&ts>0&&cs!=null)cr=cs/ts;else if(ms&&ms>0&&cs!=null)cr=cs/ms;m[c.symbol.toUpperCase()]={symbol:c.symbol,market_cap:q.market_cap||null,circulating_supply:cs,total_supply:ts,max_supply:ms,circulating_ratio:cr!=null?Math.round(cr*10000)/10000:null,cmc_rank:c.cmc_rank||null,name:c.name||c.symbol,percent_change_7d:q.percent_change_7d!=null?Math.round(q.percent_change_7d*100)/100:null,price:q.price!=null?Math.round(q.price*10000)/10000:null,volume_24h_usdt:q.volume_24h!=null?Math.round(q.volume_24h*100)/100:null};}return m}
async function fCG(env){const c=new AbortController;try{const h={'User-Agent':'CryptoScreener/5.0'};const cgK=env?.COINGECKO_API_KEY||(typeof COINGECKO_API_KEY!==`undefined`?COINGECKO_API_KEY:null);if(cgK)h['x-cg-demo-api-key']=cgK;const pages=[1,2,3,4,5,6,7,8];const r=[];for(const p of pages){const t=setTimeout(()=>c.abort(),15e3);try{const x=await fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=250&page='+p+'&sparkline=false&price_change_percentage=7d',{headers:h,signal:c.signal});if(!x.ok)throw new Error('CG p'+p+' '+x.status);try{r.push({status:'fulfilled',value:await x.json()})}catch(e){r.push({status:'rejected',reason:e})}}catch(e){r.push({status:'rejected',reason:e})}finally{clearTimeout(t)}await new Promise(d=>setTimeout(d,1300))}const m={};for(const result of r){if(result.status!=='fulfilled'||!Array.isArray(result.value))continue;for(const c of result.value){const sym=(c.symbol||'').toUpperCase();if(m[sym])continue;const cs=c.circulating_supply,ts=c.total_supply;let cr=null;if(ts&&ts>0&&cs!=null)cr=cs/ts;m[sym]={symbol:sym,market_cap:c.market_cap||null,circulating_supply:cs,total_supply:ts,max_supply:c.max_supply||null,circulating_ratio:cr!=null?Math.round(cr*10000)/10000:null,cmc_rank:c.market_cap_rank||null,name:c.name||sym,percent_change_7d:c.price_change_percentage_7d_in_currency!=null?Math.round(c.price_change_percentage_7d_in_currency*100)/100:null,price:c.current_price!=null?Math.round(c.current_price*10000)/10000:null,volume_24h_usdt:c.total_volume!=null?Math.round(c.total_volume*100)/100:null}}}console.log('CG:'+Object.keys(m).length+' coins');return Object.keys(m).length>0?m:null}catch(e){console.error('CG err:',e);return null}}
function aS(mcap,cr,conflicted,staleCg){if(mcap==null||cr==null||mcap<15e6)return 0;const raw=cS(mcap,cr);if(conflicted)return staleCg?Math.max(1,raw-1):raw;return raw}
function cS(mcap,cr){if(mcap<=5e8&&cr<0.3)return 5;if(mcap<=1e8&&cr<0.5)return 4;if(mcap<=5e8&&cr<0.5)return 3;if(mcap<=2e9&&cr<0.5)return 3;if(mcap>2e9)return cr>=0.5?1:2;if(cr>=0.8)return 1;return 2}
function uL(cr){if(cr==null)return '\u26a0\ufe0f \u672a\u77e5';if(cr<0.3)return '\ud83d\udd34 \u9ad8\u901a\u80c0\u98ce\u9669';if(cr<0.5)return '\ud83d\udfe1 \u89e3\u9501\u98ce\u9669';return '\ud83d\udfe2 \u4f4e\u98ce\u9669'}
addEventListener('fetch', event => {
  const url=new URL(event.request.url),path=normalizePath(url.pathname);
  if(event.request.method==='OPTIONS')return event.respondWith(new Response(null,{headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,X-Auth-Key'}}));
  if(path==='/api/debug-exchange')return event.respondWith(hDD(MARKET_DATA));
  if(path==='/api/data')return event.respondWith(hDA(MARKET_DATA));
  if(path==='/api/refresh'&&event.request.method==='POST')return event.respondWith(hRF(MARKET_DATA));
  if(path==='/api/upload'&&event.request.method==='POST')return event.respondWith(hUP(event.request,MARKET_DATA));
  if(path==='/api/relay-tickers'&&event.request.method==='POST')return event.respondWith(hRL(event.request,MARKET_DATA));
  if(path==='/api/status')return event.respondWith(hST(MARKET_DATA));
  event.respondWith(hDB(MARKET_DATA));
});
addEventListener('scheduled', event => {
  event.waitUntil((async()=>{console.log('Refresh start');await refreshData(MARKET_DATA,{});await hDD(MARKET_DATA).catch(()=>{});console.log('Refresh done')})());
});
async function hDA(kv){const r=await kv.get('data'),u=await kv.get('last_updated');if(!r)return json({ok:false,error:'no data',data:[],updated:null});const p=JSON.parse(r);return json({ok:true,updated:u,data:p,count:p.length})}
async function hDB(kv){const h=await kv.get(KV_HTML_KEY);if(h)return html(h);return new Response('No dashboard',{status:503})}
async function hRF(kv){const mem=await kv.get('data');console.log('Refresh start, current:',mem?JSON.parse(mem).length:0);await refreshData(kv,{});const u=await kv.get('last_updated'),c=await kv.get('count');return json({ok:true,updated:u,coins:parseInt(c||'0')})}
async function hUP(req,kv){const k=UPLOAD_AUTH_KEY,a=req.headers.get('X-Auth-Key');if(!k||a!==k)return json({ok:false,error:'Unauthorized'},401);try{const b=await req.json();if(!Array.isArray(b))return json({ok:false,error:'Must be array'},400);await kv.put('data',JSON.stringify(b));const n=new Date().toISOString();await kv.put('last_updated',n);await kv.put('count',String(b.length));return json({ok:true,coins:b.length,updated:n})}catch(e){return json({ok:false,error:e.message},400)}}
async function hRL(req,kv){const k=RELAY_AUTH_KEY,a=req.headers.get('X-Auth-Key');if(!k||a!==k)return json({ok:false,error:'Unauthorized'},401);try{const b=await req.json();if(!b||typeof b!=='object')return json({ok:false,error:'Must be object'},400);await kv.put('exchange_proxy',JSON.stringify(b));const n=new Date().toISOString();await kv.put('exchange_proxy_updated',n);const s=[];if(b.binance)s.push('binance:'+b.binance.length);if(b.bybit)s.push('bybit:'+b.bybit.length);if(b.okx)s.push('okx:'+b.okx.length);return json({ok:true,sources:s.join(', '),updated:n})}catch(e){return json({ok:false,error:e.message},400)}}
async function hST(kv){const r=await kv.get('data'),u=await kv.get('last_updated'),c=await kv.get('count');return json({project:'\u7b79\u7801\u7b5b\u9009',ok:!!r,coins:parseInt(c||'0'),updated:u})}
async function hDD(kv){const eps=[{n:'BN',u:'https://fapi.binance.com/fapi/v1/ticker/24hr?symbol=BTCUSDT'},{n:'BN spot',u:'https://api.binance.com/api/v3/ticker/24hr?symbol=BTCUSDT'},{n:'BB',u:'https://api.bybit.com/v5/market/tickers?category=linear&symbol=BTCUSDT'},{n:'OKX',u:'https://www.okx.com/api/v5/market/ticker?instId=BTC-USDT-SWAP'}];const r={};for(const ep of eps){const c=new AbortController,t=setTimeout(()=>c.abort(),1e4);try{const res=await fetch(ep.u,{signal:c.signal});clearTimeout(t);const txt=await res.text().catch(()=>'');r[ep.n]={s:res.status,p:txt.slice(0,100)}}catch(e){clearTimeout(t);r[ep.n]={e:e.message}}}await kv.put('debug_exchange',JSON.stringify(r)).catch(()=>{});return json(r)}
